server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
    gateway:
      routes:
        - id: demo-service-provider
          uri: lb://demo-service-provider
          predicates:
            - Path=/api/**
    sentinel:
      transport:
        dashboard: localhost:8500
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE;